package:
  name: nftables-slim
  version: "1.1.3"
  epoch: 0
  description: Netfilter tables userspace tools without interactive CLI
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - flex
      - libmnl-dev
      - libnftnl-dev

# Disable the test pipeline until fixing the CI job elastic-build
pipeline:
  - uses: fetch
    with:
      expected-sha256: 9c8a64b59c90b0825e540a9b8fcb9d2d942c636f81ba50199f068fde44f34ed8
      uri: https://netfilter.org/projects/nftables/files/nftables-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --sbindir=/usr/bin \
        --without-cli \
        --with-mini-gmp \
        --disable-man-doc \
        --disable-debug \

  - uses: autoconf/make

  - uses: autoconf/make-install
    with:
      opts: dist_pkgdoc_SCRIPTS=''

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 2082
